baseURL   = "https://www.itontap.tech/"
languageCode = "en-us"
title     = "ITonTAP Home"
theme     = "ananke"

[menu]

  [[menu.main]]
    name = "Podcast"
    url = "/podcast/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Hack The Box"
    url = "/hackthebox/"
    weight = 3
    identifier = "htb"   # Unique identifier for this parent

  [[menu.main]]
    name = "Challenges"
    url = "/tags/challenges/"
    weight = 4
    parent = "htb"       # This makes it a submenu under Hack The Box

  [[menu.main]]
    name = "Machines"
    url = "/tags/machines/"
    weight = 5
    parent = "htb"       # This makes it a submenu under Hack The Box


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true

[params]
  customCSS = ["css/terminal.css"]

