baseURL   = "https://www.itontap.tech/"
languageCode = "en-us"
title     = "ITonTAP Blog"
theme     = "ananke"

[menu]
  [[menu.main]]
    name = "Podcast"
    url = "/podcast/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

