baseURL   = "https://www.itontap.tech/"
languageCode = "en-us"
title     = "ITonTAP Home"
theme     = "ananke"

[menu]
  [[menu.main]]
    name = "Podcast"
    url = "/podcast/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true

