name: Build & Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and build on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/itontap-blog
            git pull
            hugo --gc --minify
